name: Test action
on:
  workflow_call:
    outputs:
      output1:
        description: "The first output string"
        value: ${{ 'Hello world' }}
#  push:
jobs:
  test-job:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

#    - uses: actions/setup-node@v1
#      name: 'setup node'
#      with:
#        node-version: '16.16.0'
#
#    - name: 'install'
#      run: npm i
#
#    - name: 'test lint'
#      run: npm run lint
#
#    - name: 'test ts'
#      run: npm run ts
#
#    - name: 'test react'
#      id: test-react
#      run: npm run test
