name: Release action
on:
  push:
jobs:
  test-job:
    uses: ./.github/workflows/action.yml

  make-release-ticket-tandex:
    runs-on: ubuntu-latest
    needs: test-job
    if: true == true
    steps:
      - uses: actions/checkout@v2

      - uses: ./.github/workflows/action.yml

      - name: Install jq
        run: sudo apt-get install -y jq

      - name: Make release ticket yandex
        run: sh ./scripts/release.sh