name: Release action
on:
  push:
jobs:
  test-job:
    uses: ./.github/workflows/action.yml

  make-release-ticket-tandex:
    runs-on: ubuntu-latest
    needs: test-job
    if: needs.test-job.outputs.last-test-status == 'true'
    steps:
      - run: echo ${{ needs.test-job.outputs.output1 }}
      - uses: actions/checkout@v2

#      - name: Install jq
#        run: sudo apt-get install -y jq
#
#      - name: Make release ticket yandex
#        run: sh ./scripts/release.sh