name: Release action
on:
  push:
#    tags:
#      - 'rc-*.*.*'

jobs:
#  test-job:
#    uses: ./.github/workflows/action.yml

  make-release-ticket-yandex:
    runs-on: ubuntu-latest
#    needs: test-job
#    if: needs.test-job.outputs.is-test-passed == 'true'

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set env
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
#      - name: Test
#        run: |
#          echo $RELEASE_VERSION
#          echo ${{ env.RELEASE_VERSION }}
      - name: Install jq
        run: sudo apt-get install -y jq
#
#      - name: Build docker
#        run: docker build . --file Dockerfile --tag $RELEASE_VERSION
      - name: Make release ticket yandex
        run: sh ./scripts/release.sh
        env:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          ORG_ID: ${{ secrets.ORG_ID }}