name: Release action
on:
  push:
jobs:

  make-release-ticket-tandex:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: ./.github/workflows/test.yml

      - name: Install jq
        run: sudo apt-get install -y jq

      - name: Make release ticket yandex
        run: sh ./scripts/release.sh