name: Release action
on:
  push:
jobs:
  call-workflow-test-in-local-repo:
    uses: ./.github/workflows/test.yml

  make-release-ticket-tandex:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install jq
        run: sudo apt-get install -y jq

      - name: Make release ticket yandex
        run: sh ./scripts/release.sh